language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: S3UTsclyWl4Rj0/X3klY7cafparq0eQ3uZxfaHCkIuenmYRjqRDL56ruO/MQB/0C9wwLmmBseFw11S8W2YiKcIlG/mdFK8bmgW/EQJip9d70JSOjXaTN+cpSz0gjjJUcWEHbE/u/87M6oDRXjdyU5nnjrbDRo1x/+kMiARa4V5xbrvoSBBzjqlBPG4LPDs+TP5g3AH0Ycx8lY4tWXuSDPb/4e2ucAKv4QKxsPpaDHX+jcEY5sgGO6JoWroKvi6QUYDDZYJZo295iPf7cFWc50AFULcnN7nCtkg97iRav2ZgD+8zBa5639hpGmuJddOhHonxtTzgtXlgUVfKu4wjmhkemQqCrMYnthBBLMgB0omG5GibwA/wnqKp4/dCND8+qrR1WjdMKHixod5yRiAr6CmoLd4ax16HFngXSNonCe9kuR4vVyL5IWCB+2HWNA1ikPZEu/ZFrPkK5+JL2D/LkkjbfcnugByqnR8hnu90mz+DvTL9VrZvieSbyz/Ce7Cdxqf8QN5iAsws+EV+NW1iBvEVW61JYv8KOxy0WJdcaGw5Cc5zaP4kdGmQHU9zzNqrovOx+lf1zZMlzOr4hCe954EEDbVULVBY7YAZ5JQWM37e3GnsZt1yoDcHVg6mOh2pfo9xCunx2jL1JRVn3IUUYIY5zPJqeQMQyhIT0jnQlttc=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
