language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: TgnnPe3/YUeUdcDSG8wk6UeYbxF9JEVxdwNlm4MyGMoMLQM41HSRGFxCHr6g4wLaIKl0qKw6+NYwUu4MXST3UmxEUYdmWw+TlSDzN3eAdVW32H9RayrN0gSzZwaZVBCjQ6dIirnLl1pqxQzVxHfEqnDTyn5JQNwBLEm/eHTBk0asckq9KaOXXQrJQMiaihHYHHNLx1fCRZ3W6zcY/1i6Ah5loN4JS/iZMThbrtqx3Hml7ZZNnZ+RVt55Tv+KU7vbnOmYqg3nAwjfsaL93PbxJf3maRwI044jQ0CInsGdBnrVMBpXqA+5s5cYdnYOwFxWeQB4CI5BDHua891b9hOEMp2bD/4CDfU2x7IvydM17+OjNwM4b1HysqLwNatWtvdjzISJMOpv456IRXB2uLkSG7ArbWmAYFdxg5A0aAht67vin7IL363mwlx88VJbMBWS0iuBVjzPZ+HRs/vf0CmUuuyTdlqU4yFF0f8syNSpPbt3POxZIu88a0paKfdwIlFij39/2FDBmulsU6q6P7Ek07qxgmuwMkKJ0zexz6vTLvR31aTmfYlsWXRjcJmsk54+j5z+mJN9RASt/0dqcqwBE6b8g24jwF3gzn3ikebf7FwMuaTNUYQ+pJs/Rpo+H9kmAz10JrFg9df0EK0m6b17M+LcXeGVheCTbb9Q1lh/KjQ=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
