language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: hjfVx/4bLaZ1j+5l4EJC5uD1ze5vAq7gDFJfORGNml9PA1n4mEIZy9uTe28cHxcx3bIYg6XBmN+469GoE0cD4Y9i91lgVS+KBXr2NdWnOS/40gpSQkb/AxvjR64TJ6rPAPYPLHcyrjkuK6xH7WuxfoZoVBZpWatJluoHGeOI1LOTlN3nR2+6WLeaA8cg2OM2ackH0Hqzv2aKMLzyhnVqoyD8QMeuMkkZgay4ESPX9KT229whK1adRzsXXvUySU2HifWUz8wpWPl06ELgXHLWgiqeetY46a6ZQ+L9cUkVhcIrIUzbDqyuyJpetETTnM6JiNFLQTAi2P8RwPHn+KzEBx536tIBHcVlq9mOwkbGcIok1Af9WjItvza3rO5hal5ucczDBIxr3zbIAAt5Of6eOEqq1DVGdzh8GpRtNHQaA4VxLfqgeC61dbkxQhOh5f8mTyPW1pBK4qmzoSyRbsusRGROPa9wpVkGO1+NsqMwuv89qLSr2UUDcTxeO0b5rjbp4klmoVa6iu4R+r23/gk8RZjEJz8WByrbrSDcr8xk3BWHfwNUeIqtRMI2B4qWPPPjcdkblLrK9yeqveNxScjRd2xQl2mwzIbgek9efcDP3fHaQ8YKR9NHlnF1/Jy+m6Q1Ra1ZJ71Y4mzMX/GKSU8n11PHvgnqt1+n7OvKewJMKzY=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
